language: python
sudo: false

env:
  matrix:
    - PYTHON=2.7 NUMPY=1.10.4 COVERAGE='false'
    - PYTHON=2.7 NUMPY=1.11.0 COVERAGE='false'
    - PYTHON=3.4 NUMPY=1.10.4 COVERAGE='false'
    - PYTHON=3.5 NUMPY=1.11.0 COVERAGE='true'

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Install dependencies
  - conda create -n test-environment python=$PYTHON
  - source activate test-environment
  - conda install numpy=$NUMPY pandas scipy multipledispatch matplotlib pytest pytest-cov 

  # Install package
  # (from dask) - pip install --no-deps -e .[complete]
  # taken from danielfrg/word2vec
  - python setup.py bdist_wheel
  - ls dist
  - pip install --pre --no-index --find-links dist/ pennies

script:
  - if [[ $COVERAGE == 'true' ]]; then py.test --cov --cov-report=html -vv -s --pyarg --doctest-modules pennies; fi

after_success:
  - if [[ COVERAGE == 'true' ]]; then coverage report --show-missing; pip install coveralls ; coveralls ; fi

#notifications:
#  email: false
