language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  # Install conda
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install --file requirements.txt

  # Install package
  # (from dask) - pip install --no-deps -e .[complete]
  # taken from danielfrg/word2vec
  - python setup.py bdist_wheel
  - ls dist
  - pip install --pre --no-index --find-links dist/ pennies

script:
  - py.test --cov --cov-report=html -vv -s --pyarg --doctest-modules pennies

after_success:
  - coverage report --show-missing
  - pip install coveralls
  - coveralls

#notifications:
#  email: false
